version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: maks
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: fastDb
    ports:
      - "5432:5432"


  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
